packages:
  - client
  - server
  - shared/types
  - shared/emails
allowBuilds:
  '@tailwindcss/oxide': true
  better-sqlite3: true
  bufferutil: true
  core-js: true
  esbuild: true
  sharp: true
overrides:
  '@types/react': 19.2.18
  '@types/react-dom': 19.2.5
  next: 16.3.2
publicHoistPattern:
  - '*@heroui/*'
verifyDepsBeforeRun: false
forceLegacyDeploy: true
